apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: zaekv/backend:latest
        env:
          - name: ACCESS_TOKEN_SECRET
            value: itissecret
          - name: REFRESH_TOKEN_SECRET
            value: itisalsosecret
          - name: MONGODB_URL
            value: mongodb://root:example@mongo/mern?authSource=admin
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081  # Backend will be accessible on port 30081 of the node

