version: '3.8'

services:
  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    networks:
      - app-network

  backend:
    build:
      context: backend
    environment:
      ACCESS_TOKEN_SECRET: itissecret
      REFRESH_TOKEN_SECRET: itisalsosecret
      MONGODB_URL: mongodb://root:example@mongo/mern?authSource=admin
    ports:
      - 8080:8080
    networks:
      - app-network

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8081:8081
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:

